name: Prune GHCR versions
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: read
  packages: write

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - name: Install gh & jq
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Delete old container versions
        env:
          OWNER: ${{ github.repository_owner }}
          REPO: void-mklive
          PKG: void-mklive
          KEEP: 3
          DAYS: 3
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euxo pipefail

          # 1) 列出前 100 个版本
          echo "Fetching package versions..."
          VERSIONS=$(gh api \
            --method GET \
            -H "Accept: application/vnd.github+json" \
            /users/${OWNER}/packages/container/${PKG}/versions?per_page=100)

          # 2) 用 jq 筛选出：创建日期早于 N 天前，且跳过前 KEEP 个
          IDS=$(jq -r \
            --argjson keep "$KEEP" \
            --arg days "$DAYS" \
            '
              map(select(
                (.created_at | fromdateiso8601) < (now - ($days|tonumber * 86400))
              ))
              | .[$keep:]
              | .[].id
            ' <<<"$VERSIONS"
          )

          if [ -z "$IDS" ]; then
            echo "No old versions to delete."
            exit 0
          fi

          echo "Will delete the following version IDs:"
          echo "$IDS"

          # 3) 逐个删除
          echo "$IDS" | xargs -r -n1 -I{} gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            /users/${OWNER}/packages/container/${PKG}/versions/{}

          echo "Deleted $(wc -l <<<"$IDS") versions."
