name: Prune GHCR versions
on:
  schedule:
    - cron: "0 3 * * *"  # every day at 03:00 UTC

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old GHCR versions
        uses: actions/delete-package-versions@v1
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          package-name: void-mklive     # your container repo name
          num-old-versions-to-delete: 10 # keeps the 10 newest, deletes the rest
          token: ${{ secrets.GITHUB_TOKEN }}
